"""
Email Sender for AlphaVerify Monte Carlo Simulation
Sends PDF reports via Brevo (formerly Sendinblue) API.
"""
import os
import base64
import logging
from datetime import datetime
import requests

logger = logging.getLogger(__name__)


def send_monte_carlo_report(
    recipient_email: str,
    pdf_bytes: bytes,
    mean_return: float,
    max_drawdown_95: float,
    risk_of_ruin: float,
    n_simulations: int,
    n_trades: int
) -> bool:
    """
    Send Monte Carlo report via Brevo API.
    
    Requires environment variables:
    - BREVO_API_KEY: Your Brevo API key
    - BREVO_FROM_EMAIL: Your verified sender email
    - BREVO_FROM_NAME: Sender name (optional, defaults to AlphaVerify)
    
    Args:
        recipient_email: Email address to send report to
        pdf_bytes: The PDF report as bytes
        mean_return: Mean expected return percentage
        max_drawdown_95: 95th percentile max drawdown
        risk_of_ruin: Probability of ruin percentage
        n_simulations: Number of simulations run
        n_trades: Number of trades analyzed
    
    Returns:
        True if successful, raises exception otherwise
    """
    api_key = os.getenv('BREVO_API_KEY')
    from_email = os.getenv('BREVO_FROM_EMAIL')
    from_name = os.getenv('BREVO_FROM_NAME', 'AlphaVerify')
    
    if not api_key or not from_email:
        logger.error("Brevo credentials not configured.")
        # Make this non-fatal return in SuperApp context?
        # Original raised ValueError.
        return False
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    filename = f"AlphaVerify_MonteCarlo_{timestamp}.pdf"
    
    # Determine colors based on values
    return_color = "#22c55e" if mean_return >= 0 else "#ef4444"
    return_emoji = "📈" if mean_return >= 0 else "📉"
    risk_color = "#22c55e" if risk_of_ruin < 5 else ("#f59e0b" if risk_of_ruin < 20 else "#ef4444")
    
    html_body = f"""
    <html>
    <body style="font-family: Arial, sans-serif; background-color: #0f172a; color: #e2e8f0; padding: 20px;">
        <div style="max-width: 600px; margin: 0 auto;">
            <h1 style="color: #3b82f6; border-bottom: 2px solid #3b82f6; padding-bottom: 10px;">
                🎲 AlphaVerify - Monte Carlo Simulation Complete
            </h1>
            
            <p>Your Monte Carlo simulation has finished! Here's a quick overview:</p>
            
            <div style="background-color: #1e293b; padding: 20px; border-radius: 8px; margin: 20px 0;">
                <h2 style="color: #94a3b8; margin-top: 0;">Simulation Summary</h2>
                <table style="width: 100%; color: #e2e8f0;">
                    <tr>
                        <td style="padding: 8px 0;">Expected Return:</td>
                        <td style="text-align: right; color: {return_color}; font-weight: bold;">
                            {return_emoji} {mean_return:.2f}%
                        </td>
                    </tr>
                    <tr>
                        <td style="padding: 8px 0;">95% Max Drawdown VaR:</td>
                        <td style="text-align: right; color: #ef4444;">{max_drawdown_95:.2f}%</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px 0;">Risk of Ruin:</td>
                        <td style="text-align: right; color: {risk_color};">{risk_of_ruin:.2f}%</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px 0;">Simulations Run:</td>
                        <td style="text-align: right;">{n_simulations:,}</td>
                    </tr>
                    <tr>
                        <td style="padding: 8px 0;">Trades Analyzed:</td>
                        <td style="text-align: right;">{n_trades:,}</td>
                    </tr>
                </table>
            </div>
            
            <p><strong>Attached:</strong> 📊 Full PDF Report with Cone of Uncertainty charts and detailed statistical analysis.</p>
            
            <div style="background-color: #1e3a5f; padding: 15px; border-radius: 8px; margin: 20px 0; border-left: 4px solid #3b82f6;">
                <p style="margin: 0; font-size: 14px;">
                    <strong>💡 Pro Tip:</strong> The Cone of Uncertainty chart shows the range of possible 
                    equity outcomes. A narrower cone indicates more consistent performance across different 
                    trade sequences.
                </p>
            </div>
            
            <hr style="border: 1px solid #475569; margin: 30px 0;">
            <p style="color: #64748b; font-size: 12px;">
                This report was generated by AlphaVerify Monte Carlo Simulation.<br>
                Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
            </p>
        </div>
    </body>
    </html>
    """
    
    text_body = f"""
AlphaVerify - Monte Carlo Simulation Complete

Your simulation has finished!

Simulation Summary:
- Expected Return: {mean_return:.2f}%
- 95% Max Drawdown VaR: {max_drawdown_95:.2f}%
- Risk of Ruin: {risk_of_ruin:.2f}%
- Simulations Run: {n_simulations:,}
- Trades Analyzed: {n_trades:,}

Please see the attached PDF for the full report with charts and analysis.

Generated at: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
    """
    
    url = "https://api.brevo.com/v3/smtp/email"
    
    headers = {
        "api-key": api_key,
        "Content-Type": "application/json",
        "Accept": "application/json"
    }
    
    pdf_base64 = base64.b64encode(pdf_bytes).decode('utf-8')
    
    payload = {
        "sender": {
            "email": from_email,
            "name": from_name
        },
        "to": [
            {
                "email": recipient_email,
                "name": "Trader"
            }
        ],
        "subject": f"🎲 Monte Carlo Report Ready - {datetime.now().strftime('%Y-%m-%d')}",
        "htmlContent": html_body,
        "textContent": text_body,
        "attachment": [
            {
                "name": filename,
                "content": pdf_base64
            }
        ]
    }
    
    try:
        response = requests.post(url, json=payload, headers=headers)
        
        if response.status_code in [200, 201, 202]:
            logger.info(f"Monte Carlo report sent successfully to {recipient_email}")
            return True
        else:
            error_msg = response.text
            logger.error(f"Brevo API error: {response.status_code} - {error_msg}")
            # raise ValueError(f"Failed to send email: {error_msg}")
            return False
            
    except requests.RequestException as e:
        logger.error(f"Failed to send email: {e}")
        return False
